### ISSUE TITLE
App crashed on checkout

### ISSUE THREAD

**Issue by baihuqian** [xamguo/D-Food#1]
I tested your app. Everything works except when I click checkout, it crashed. Why?

**Comment by Raymind** [comment]
Probably you need to apply for your own Google Map Key and replace the
value in the code with your own.
That code is under AndroidManifest.xml.

[image: Inline image 1]

**Comment by xamguo** [comment]
Sorry about that, I thought I could show you on Wednesday. We used map API and thus used my key. That key won't work on other machines.
